services:
  load-balancer:
    image: meteo/load-balancer
    build:
        context: .
        dockerfile: load_balancer/Dockerfile
    environment:
      - PORT=50051
      - LOG_LEVEL=debug
    networks:
      - server-network
      - sensor-network
  proxy:
    image: meteo/proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    environment:
      - PORT=50050
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
    ports:
        - "50050:50050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge
    networks:
      - server-network
      - default
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - server-network
  server:
    image: meteo/server
    build:
        context: .
        dockerfile: server/Dockerfile
    environment:
      - LOAD_BALANCER_ADDRESS=load-balancer:50051
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
    networks:
      - server-network
  air-quality-sensor:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - INTERVAL=1000
      - SENSOR_TYPE=air_quality
      - METEO_SERVICE_ADDRESS=load-balancer:50051
      - LOG_LEVEL=debug
    networks:
      - sensor-network
  pollution-sensor:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - INTERVAL=1000
      - SENSOR_TYPE=pollution
      - METEO_SERVICE_ADDRESS=load-balancer:50051
      - LOG_LEVEL=debug
    networks:
      - sensor-network
networks:
  server-network:
    driver: bridge
  sensor-network:
    driver: bridge
