services:
  load-balancer:
    image: meteo/load-balancer
    build:
        context: .
        dockerfile: load_balancer/Dockerfile
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
    networks:
      - server-network
      - sensor-network
  proxy:
    image: meteo/proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    environment:
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
    networks:
      - server-network
      - terminal-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - server-network
  server:
    image: meteo/server
    build:
        context: .
        dockerfile: server/Dockerfile
    environment:
      - LOAD_BALANCER_ADDRESS=load-balancer:8080
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
    networks:
      - server-network
  air-quality-sensor:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - SENSOR_TYPE=air_quality
      - METEO_SERVICE_ADDRESS=load-balancer:8080
      - LOG_LEVEL=debug
    networks:
      - sensor-network
  pollution-sensor:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - SENSOR_TYPE=pollution
      - METEO_SERVICE_ADDRESS=load-balancer:8080
      - LOG_LEVEL=debug
    networks:
      - sensor-network
  terminal:
    image: meteo/terminal
    build:
        context: .
        dockerfile: terminal/Dockerfile
    environment:
      - PROXY_ADDRESS=proxy:8080
      - LOG_LEVEL=debug
    networks:
      - terminal-network
networks:
  server-network:
    driver: bridge
  terminal-network:
    driver: bridge
  sensor-network:
    driver: bridge
