services:
  load-balancer:
    image: meteo/load-balancer
    build:
        context: .
        dockerfile: load_balancer/Dockerfile
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
  proxy:
    image: meteo/proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    environment:
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
  server:
    image: meteo/server
    build:
        context: .
        dockerfile: server/Dockerfile
    environment:
      - LOAD_BALANCER_ADDRESS=load-balancer:8080
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
  air-quality-sensor:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - SENSOR_TYPE=air_quality
      - METEO_SERVICE_ADDRESS=load-balancer:8080
      - LOG_LEVEL=debug
  pollution-sensor:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - SENSOR_TYPE=pollution
      - METEO_SERVICE_ADDRESS=load-balancer:8080
      - LOG_LEVEL=debug
  terminal:
    image: meteo/terminal
    build:
        context: .
        dockerfile: terminal/Dockerfile
    environment:
      - PROXY_ADDRESS=proxy:8080
