services:
  load-balancer:
    image: meteo/load-balancer
    build:
        context: .
        dockerfile: load_balancer/Dockerfile
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  server1:
    image: meteo/server
    build:
        context: .
        dockerfile: server/Dockerfile
    environment:
      - LOAD_BALANCER_ADDRESS=load-balancer:8080
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
  sensor1:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - METEO_SERVICE_ADDRESS=load-balancer:8080
      - LOG_LEVEL=debug
  sensor2:
    image: meteo/sensor
    build:
        context: .
        dockerfile: sensor/Dockerfile
    environment:
      - METEO_SERVICE_ADDRESS=load-balancer:8080
      - LOG_LEVEL=debug
