# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/services/meteo/meteo_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.messages.meteo import meteo_messages_pb2 as proto_dot_messages_dot_meteo_dot_meteo__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(proto/services/meteo/meteo_service.proto\x12\x05meteo\x1a\x1bgoogle/protobuf/empty.proto\x1a)proto/messages/meteo/meteo_messages.proto2\x92\x01\n\x0cMeteoService\x12<\n\rSendMeteoData\x12\x13.meteo.RawMeteoData\x1a\x16.google.protobuf.Empty\x12\x44\n\x11SendPollutionData\x12\x17.meteo.RawPollutionData\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.services.meteo.meteo_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METEOSERVICE._serialized_start=124
  _METEOSERVICE._serialized_end=270
# @@protoc_insertion_point(module_scope)
