# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.services.terminal import terminal_service_pb2 as proto_dot_services_dot_terminal_dot_terminal__service__pb2


class TerminalServiceStub(object):
    """TerminalService is the service that is used to connect to a terminal
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendResults = channel.unary_unary(
                '/terminal.TerminalService/SendResults',
                request_serializer=proto_dot_services_dot_terminal_dot_terminal__service__pb2.Results.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TerminalServiceServicer(object):
    """TerminalService is the service that is used to connect to a terminal
    """

    def SendResults(self, request, context):
        """Send processed data to the terminal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendResults': grpc.unary_unary_rpc_method_handler(
                    servicer.SendResults,
                    request_deserializer=proto_dot_services_dot_terminal_dot_terminal__service__pb2.Results.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terminal.TerminalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TerminalService(object):
    """TerminalService is the service that is used to connect to a terminal
    """

    @staticmethod
    def SendResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/terminal.TerminalService/SendResults',
            proto_dot_services_dot_terminal_dot_terminal__service__pb2.Results.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
