# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/services/processing/processing_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.messages.meteo import meteo_messages_pb2 as proto_dot_messages_dot_meteo_dot_meteo__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2proto/services/processing/processing_service.proto\x12\x05meteo\x1a)proto/messages/meteo/meteo_messages.proto\"\'\n\x16\x41irWellnessCoefficient\x12\r\n\x05value\x18\x01 \x01(\x02\"%\n\x14PollutionCoefficient\x12\r\n\x05value\x18\x01 \x01(\x02\x32\xa9\x01\n\x11ProcessingService\x12\x46\n\x10ProcessMeteoData\x12\x13.meteo.RawMeteoData\x1a\x1d.meteo.AirWellnessCoefficient\x12L\n\x14ProcessPollutionData\x12\x17.meteo.RawPollutionData\x1a\x1b.meteo.PollutionCoefficientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.services.processing.processing_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AIRWELLNESSCOEFFICIENT._serialized_start=104
  _AIRWELLNESSCOEFFICIENT._serialized_end=143
  _POLLUTIONCOEFFICIENT._serialized_start=145
  _POLLUTIONCOEFFICIENT._serialized_end=182
  _PROCESSINGSERVICE._serialized_start=185
  _PROCESSINGSERVICE._serialized_end=354
# @@protoc_insertion_point(module_scope)
